/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type EmploymentType = { 'unemployed' : null } |
  { 'self_employed' : null } |
  { 'salaried' : null };
export interface LoanApplication {
  'status' : LoanStatus,
  'applicant' : Principal,
  'applicationId' : bigint,
  'createdAt' : Time,
  'upiTransactionId' : [] | [string],
  'updatedAt' : Time,
  'platformFeePaid' : boolean,
  'submission' : LoanApplicationSubmission,
}
export interface LoanApplicationSubmission {
  'fullName' : string,
  'email' : string,
  'employmentType' : EmploymentType,
  'tenureMonths' : bigint,
  'phone' : string,
  'amountRequested' : bigint,
  'monthlyIncome' : bigint,
  'loanProduct' : LoanProduct,
}
export type LoanProduct = { 'personal_loan' : null } |
  { 'instant_loan' : null };
export interface LoanProductDetails {
  'maxTenure' : bigint,
  'maxAmount' : bigint,
  'minTenure' : bigint,
  'name' : string,
  'description' : string,
  'interestRate' : number,
}
export type LoanStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'under_review' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelApplication' : ActorMethod<[bigint], undefined>,
  'checkApplicationStatus' : ActorMethod<[bigint], LoanStatus>,
  'getAllApplications' : ActorMethod<[], Array<LoanApplication>>,
  'getApplication' : ActorMethod<[bigint], LoanApplication>,
  'getApplicationsByStatus' : ActorMethod<[LoanStatus], Array<LoanApplication>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLoanProducts' : ActorMethod<[], Array<LoanProductDetails>>,
  'getPlatformFeePaymentStatus' : ActorMethod<[bigint], boolean>,
  'getUserApplications' : ActorMethod<[], Array<LoanApplication>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordPlatformFeePayment' : ActorMethod<[bigint, string], undefined>,
  'submitLoanApplication' : ActorMethod<[LoanApplicationSubmission], bigint>,
  'updateApplicationStatus' : ActorMethod<[bigint, LoanStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];