/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LoanStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'under_review' : IDL.Null,
});
export const Time = IDL.Int;
export const EmploymentType = IDL.Variant({
  'unemployed' : IDL.Null,
  'self_employed' : IDL.Null,
  'salaried' : IDL.Null,
});
export const LoanProduct = IDL.Variant({
  'personal_loan' : IDL.Null,
  'instant_loan' : IDL.Null,
});
export const LoanApplicationSubmission = IDL.Record({
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'employmentType' : EmploymentType,
  'tenureMonths' : IDL.Nat,
  'phone' : IDL.Text,
  'amountRequested' : IDL.Nat,
  'monthlyIncome' : IDL.Nat,
  'loanProduct' : LoanProduct,
});
export const LoanApplication = IDL.Record({
  'status' : LoanStatus,
  'applicant' : IDL.Principal,
  'applicationId' : IDL.Nat,
  'createdAt' : Time,
  'upiTransactionId' : IDL.Opt(IDL.Text),
  'updatedAt' : Time,
  'platformFeePaid' : IDL.Bool,
  'submission' : LoanApplicationSubmission,
});
export const LoanProductDetails = IDL.Record({
  'maxTenure' : IDL.Nat,
  'maxAmount' : IDL.Nat,
  'minTenure' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'interestRate' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelApplication' : IDL.Func([IDL.Nat], [], []),
  'checkApplicationStatus' : IDL.Func([IDL.Nat], [LoanStatus], ['query']),
  'getAllApplications' : IDL.Func([], [IDL.Vec(LoanApplication)], ['query']),
  'getApplication' : IDL.Func([IDL.Nat], [LoanApplication], ['query']),
  'getApplicationsByStatus' : IDL.Func(
      [LoanStatus],
      [IDL.Vec(LoanApplication)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLoanProducts' : IDL.Func([], [IDL.Vec(LoanProductDetails)], ['query']),
  'getPlatformFeePaymentStatus' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'getUserApplications' : IDL.Func([], [IDL.Vec(LoanApplication)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordPlatformFeePayment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'submitLoanApplication' : IDL.Func(
      [LoanApplicationSubmission],
      [IDL.Nat],
      [],
    ),
  'updateApplicationStatus' : IDL.Func([IDL.Nat, LoanStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LoanStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'under_review' : IDL.Null,
  });
  const Time = IDL.Int;
  const EmploymentType = IDL.Variant({
    'unemployed' : IDL.Null,
    'self_employed' : IDL.Null,
    'salaried' : IDL.Null,
  });
  const LoanProduct = IDL.Variant({
    'personal_loan' : IDL.Null,
    'instant_loan' : IDL.Null,
  });
  const LoanApplicationSubmission = IDL.Record({
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'employmentType' : EmploymentType,
    'tenureMonths' : IDL.Nat,
    'phone' : IDL.Text,
    'amountRequested' : IDL.Nat,
    'monthlyIncome' : IDL.Nat,
    'loanProduct' : LoanProduct,
  });
  const LoanApplication = IDL.Record({
    'status' : LoanStatus,
    'applicant' : IDL.Principal,
    'applicationId' : IDL.Nat,
    'createdAt' : Time,
    'upiTransactionId' : IDL.Opt(IDL.Text),
    'updatedAt' : Time,
    'platformFeePaid' : IDL.Bool,
    'submission' : LoanApplicationSubmission,
  });
  const LoanProductDetails = IDL.Record({
    'maxTenure' : IDL.Nat,
    'maxAmount' : IDL.Nat,
    'minTenure' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'interestRate' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelApplication' : IDL.Func([IDL.Nat], [], []),
    'checkApplicationStatus' : IDL.Func([IDL.Nat], [LoanStatus], ['query']),
    'getAllApplications' : IDL.Func([], [IDL.Vec(LoanApplication)], ['query']),
    'getApplication' : IDL.Func([IDL.Nat], [LoanApplication], ['query']),
    'getApplicationsByStatus' : IDL.Func(
        [LoanStatus],
        [IDL.Vec(LoanApplication)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLoanProducts' : IDL.Func([], [IDL.Vec(LoanProductDetails)], ['query']),
    'getPlatformFeePaymentStatus' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'getUserApplications' : IDL.Func([], [IDL.Vec(LoanApplication)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordPlatformFeePayment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'submitLoanApplication' : IDL.Func(
        [LoanApplicationSubmission],
        [IDL.Nat],
        [],
      ),
    'updateApplicationStatus' : IDL.Func([IDL.Nat, LoanStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };