/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface LoanApplicationSubmission {
    fullName: string;
    email: string;
    employmentType: EmploymentType;
    tenureMonths: bigint;
    phone: string;
    amountRequested: bigint;
    monthlyIncome: bigint;
    loanProduct: LoanProduct;
}
export interface LoanApplication {
    status: LoanStatus;
    applicant: Principal;
    applicationId: bigint;
    createdAt: Time;
    upiTransactionId?: string;
    updatedAt: Time;
    platformFeePaid: boolean;
    submission: LoanApplicationSubmission;
}
export interface LoanProductDetails {
    maxTenure: bigint;
    maxAmount: bigint;
    minTenure: bigint;
    name: string;
    description: string;
    interestRate: number;
}
export enum EmploymentType {
    unemployed = "unemployed",
    self_employed = "self_employed",
    salaried = "salaried"
}
export enum LoanProduct {
    personal_loan = "personal_loan",
    instant_loan = "instant_loan"
}
export enum LoanStatus {
    cancelled = "cancelled",
    pending = "pending",
    approved = "approved",
    rejected = "rejected",
    under_review = "under_review"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelApplication(id: bigint): Promise<void>;
    checkApplicationStatus(id: bigint): Promise<LoanStatus>;
    getAllApplications(): Promise<Array<LoanApplication>>;
    getApplication(id: bigint): Promise<LoanApplication>;
    getApplicationsByStatus(status: LoanStatus): Promise<Array<LoanApplication>>;
    getCallerUserRole(): Promise<UserRole>;
    getLoanProducts(): Promise<Array<LoanProductDetails>>;
    getPlatformFeePaymentStatus(applicationId: bigint): Promise<boolean>;
    getUserApplications(): Promise<Array<LoanApplication>>;
    isCallerAdmin(): Promise<boolean>;
    recordPlatformFeePayment(applicationId: bigint, upiTransactionId: string): Promise<void>;
    submitLoanApplication(submission: LoanApplicationSubmission): Promise<bigint>;
    updateApplicationStatus(id: bigint, status: LoanStatus): Promise<void>;
}
import type { EmploymentType as _EmploymentType, LoanApplication as _LoanApplication, LoanApplicationSubmission as _LoanApplicationSubmission, LoanProduct as _LoanProduct, LoanStatus as _LoanStatus, Time as _Time, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelApplication(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelApplication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelApplication(arg0);
            return result;
        }
    }
    async checkApplicationStatus(arg0: bigint): Promise<LoanStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.checkApplicationStatus(arg0);
                return from_candid_LoanStatus_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkApplicationStatus(arg0);
            return from_candid_LoanStatus_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllApplications(): Promise<Array<LoanApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApplications();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApplications();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApplication(arg0: bigint): Promise<LoanApplication> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplication(arg0);
                return from_candid_LoanApplication_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplication(arg0);
            return from_candid_LoanApplication_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApplicationsByStatus(arg0: LoanStatus): Promise<Array<LoanApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplicationsByStatus(to_candid_LoanStatus_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplicationsByStatus(to_candid_LoanStatus_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLoanProducts(): Promise<Array<LoanProductDetails>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoanProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoanProducts();
            return result;
        }
    }
    async getPlatformFeePaymentStatus(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformFeePaymentStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformFeePaymentStatus(arg0);
            return result;
        }
    }
    async getUserApplications(): Promise<Array<LoanApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserApplications();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserApplications();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordPlatformFeePayment(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPlatformFeePayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPlatformFeePayment(arg0, arg1);
            return result;
        }
    }
    async submitLoanApplication(arg0: LoanApplicationSubmission): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLoanApplication(to_candid_LoanApplicationSubmission_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLoanApplication(to_candid_LoanApplicationSubmission_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateApplicationStatus(arg0: bigint, arg1: LoanStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApplicationStatus(arg0, to_candid_LoanStatus_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApplicationStatus(arg0, to_candid_LoanStatus_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_EmploymentType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmploymentType): EmploymentType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_LoanApplicationSubmission_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoanApplicationSubmission): LoanApplicationSubmission {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_LoanApplication_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoanApplication): LoanApplication {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_LoanProduct_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoanProduct): LoanProduct {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_LoanStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoanStatus): LoanStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fullName: string;
    email: string;
    employmentType: _EmploymentType;
    tenureMonths: bigint;
    phone: string;
    amountRequested: bigint;
    monthlyIncome: bigint;
    loanProduct: _LoanProduct;
}): {
    fullName: string;
    email: string;
    employmentType: EmploymentType;
    tenureMonths: bigint;
    phone: string;
    amountRequested: bigint;
    monthlyIncome: bigint;
    loanProduct: LoanProduct;
} {
    return {
        fullName: value.fullName,
        email: value.email,
        employmentType: from_candid_EmploymentType_n11(_uploadFile, _downloadFile, value.employmentType),
        tenureMonths: value.tenureMonths,
        phone: value.phone,
        amountRequested: value.amountRequested,
        monthlyIncome: value.monthlyIncome,
        loanProduct: from_candid_LoanProduct_n13(_uploadFile, _downloadFile, value.loanProduct)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _LoanStatus;
    applicant: Principal;
    applicationId: bigint;
    createdAt: _Time;
    upiTransactionId: [] | [string];
    updatedAt: _Time;
    platformFeePaid: boolean;
    submission: _LoanApplicationSubmission;
}): {
    status: LoanStatus;
    applicant: Principal;
    applicationId: bigint;
    createdAt: Time;
    upiTransactionId?: string;
    updatedAt: Time;
    platformFeePaid: boolean;
    submission: LoanApplicationSubmission;
} {
    return {
        status: from_candid_LoanStatus_n3(_uploadFile, _downloadFile, value.status),
        applicant: value.applicant,
        applicationId: value.applicationId,
        createdAt: value.createdAt,
        upiTransactionId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.upiTransactionId)),
        updatedAt: value.updatedAt,
        platformFeePaid: value.platformFeePaid,
        submission: from_candid_LoanApplicationSubmission_n9(_uploadFile, _downloadFile, value.submission)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unemployed: null;
} | {
    self_employed: null;
} | {
    salaried: null;
}): EmploymentType {
    return "unemployed" in value ? EmploymentType.unemployed : "self_employed" in value ? EmploymentType.self_employed : "salaried" in value ? EmploymentType.salaried : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    personal_loan: null;
} | {
    instant_loan: null;
}): LoanProduct {
    return "personal_loan" in value ? LoanProduct.personal_loan : "instant_loan" in value ? LoanProduct.instant_loan : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    under_review: null;
}): LoanStatus {
    return "cancelled" in value ? LoanStatus.cancelled : "pending" in value ? LoanStatus.pending : "approved" in value ? LoanStatus.approved : "rejected" in value ? LoanStatus.rejected : "under_review" in value ? LoanStatus.under_review : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LoanApplication>): Array<LoanApplication> {
    return value.map((x)=>from_candid_LoanApplication_n6(_uploadFile, _downloadFile, x));
}
function to_candid_EmploymentType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmploymentType): _EmploymentType {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_LoanApplicationSubmission_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoanApplicationSubmission): _LoanApplicationSubmission {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_LoanProduct_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoanProduct): _LoanProduct {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_LoanStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoanStatus): _LoanStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fullName: string;
    email: string;
    employmentType: EmploymentType;
    tenureMonths: bigint;
    phone: string;
    amountRequested: bigint;
    monthlyIncome: bigint;
    loanProduct: LoanProduct;
}): {
    fullName: string;
    email: string;
    employmentType: _EmploymentType;
    tenureMonths: bigint;
    phone: string;
    amountRequested: bigint;
    monthlyIncome: bigint;
    loanProduct: _LoanProduct;
} {
    return {
        fullName: value.fullName,
        email: value.email,
        employmentType: to_candid_EmploymentType_n21(_uploadFile, _downloadFile, value.employmentType),
        tenureMonths: value.tenureMonths,
        phone: value.phone,
        amountRequested: value.amountRequested,
        monthlyIncome: value.monthlyIncome,
        loanProduct: to_candid_LoanProduct_n23(_uploadFile, _downloadFile, value.loanProduct)
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoanStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    under_review: null;
} {
    return value == LoanStatus.cancelled ? {
        cancelled: null
    } : value == LoanStatus.pending ? {
        pending: null
    } : value == LoanStatus.approved ? {
        approved: null
    } : value == LoanStatus.rejected ? {
        rejected: null
    } : value == LoanStatus.under_review ? {
        under_review: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmploymentType): {
    unemployed: null;
} | {
    self_employed: null;
} | {
    salaried: null;
} {
    return value == EmploymentType.unemployed ? {
        unemployed: null
    } : value == EmploymentType.self_employed ? {
        self_employed: null
    } : value == EmploymentType.salaried ? {
        salaried: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoanProduct): {
    personal_loan: null;
} | {
    instant_loan: null;
} {
    return value == LoanProduct.personal_loan ? {
        personal_loan: null
    } : value == LoanProduct.instant_loan ? {
        instant_loan: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
